youtube/youtube-ios-player-helper

Classes/YTPlayerView.h, Project/youtube-player-ios-example/youtube-player-ios-example/SingleVideoViewController.m
This should fix https://github.com/youtube/youtube-ios-player-helper/issues/21 - converted the current enums to NS_ENUM for Swift compatibility. I tested on hardware but didn't think new unit tests would be necessary.
=> Converted enums to NS_ENUM for Swift compatibility.

Classes/YTPlayerView.m
Resolves incorrect URI format documentation, which was mistakenly using 'http' schemes.
=> Correct documentation of URI format

Classes/YTPlayerView.m
[UIWebview stringByEvaluatingJavaScriptFromString: ] only returns the correct data if the data is string
When executing player.getAvailablePlaybackRates(); it returns an array, so the quality array will never
be passed to the Objective C array.
fixed this issue by adding toString() on the javascript command, and parse the returned string int a NSArray
with [NSString componentsSeparatedByString:]
=> fix the issue when UIWebView javascript returns array

Assets/YTPlayerView-iframe-player.html, Classes/YTPlayerView.m
Not sure if this affects other video aspect ratios but it was the only way to keep the lib from cutting off the bottom in my app. Let me know if you think there's a better way to approach this issue.
=> Fixed cut-off bottom of 16:9 videos

Classes/YTPlayerView.h, Classes/YTPlayerView.m
This pull request adds a constant to account for cases when "Auto" quality is returned from YouTube. I've found this happens mostly when watching YouTube Live Events with the `YTPlayerView`.  I have modified this PR from #55 to adhere to more of the guidelines for contributing.
Tested on iPhones 4s through 6 Plus running iOS 8.1.x.  Please let me know if you need any more information.  I have signed the individual CLA.
=> Added 'Auto' Quality Constant

Classes/YTPlayerView.h, Classes/YTPlayerView.m
Ragarding the documentation for API V3 youtube also sends error code 150 for not embeddeable videos - https://developers.google.com/youtube/iframe_api_reference#onError
Cheers
Max
=> Added handling for error 150, according to the documentation for v3 API

Assets/YTPlayerView-iframe-player.html, Classes/YTPlayerView.m
“origin” property should be part of playerVars and should be set / get from there, in the current implementation “origin” cannot be passed to the loading process from the host class nor is been set correctly to the playerVars json object been passed to the page.
=> Issue with origin not been part of playerVars

Classes/YTPlayerView.m
The patch fixes the issues discussed in #109.  I have added additional regular expressions to prevent the UIWebView from taking the user out of the app when loading any URLs that look like https://accounts.google.com/o/oauth2/ or https://content.googleapis.com/static/proxy.html.
This is mainly a fix for Live Event videos.  Tested with Video IDs `w-T2LJ_qLiw`, `nrYHu7hmMK0`, and `wpZNaYN29xs`.
@iulukaya please review and merge.
=> Fixing OAuth redirect issue

Classes/YTPlayerView.m, youtube-ios-player-helper.podspec
#107 the thing was that when using CocoaPods with Swift, It makes a framework from each dependency, and each framework has it's own bundle
=> Fix missed resources issue when using CocoaPods with Swift

Classes/YTPlayerView.h, Classes/YTPlayerView.m
I wanted to be able to ensure the background matched in my app. Or more to the point, it inherited what was beneath it.
I've implemented an optional delegate callback allowing it to be specified if required. Tested and working using a pod reference to my repo (sadly in a private project).
=> Allowing custom styling of the webview background

youtube-ios-player-helper.podspec
In order for changes to kick in you must push fixed `.podspec` file to repository. 
**And check in future if your stuff is working before releasing it.**
You may need to remove your cached `youtube-ios-player-helper` pod from working folder and global cache folder, and pull pods again, like [here](https://gist.github.com/mbinna/4202236).
* #157
* #160
=> Fixes #157 and #160

Classes/YTPlayerView.h, Classes/YTPlayerView.m, youtube-ios-player-helper/Assets.bundle/Assets/YTPlayerView-iframe-player.html
Hello, I'm heavily using this library to show YouTube videos to my users and I found adding a loading view while the view is loading YouTube iframe is just too mandatory so I've made this PR as I'm privately doing in my own code. Also I want to add nullability specifiers to all public APIs for better Swift portability and added some comments to public APIs.
The changeset is kinda huge, do you wish to split the PR?
=> Added comments, Added nullability specifiers, Added -playerViewPreferredInitialLoadingView:

Classes/YTPlayerView.h, Classes/YTPlayerView.m, Project/youtube-player-ios-example/youtube-player-ios-exampleTests/youtube_player_ios_exampleTests.m
"January 6, 2016 - The clearVideo function has been deprecated and removed from the documentation. The function no longer has any effect in the YouTube player."
Source: https://developers.google.com/youtube/iframe_api_reference#clearVideo
=> Remove deprecated method: clearVideo

Classes/YTPlayerView.m
When testing the following video: https://www.youtube.com/watch?v=ku6cI5v70MQ
I noticed that right before the Advertisement started, the SDK would call [application openURL: ..] on a url that would render a blank page. Since this is not the best user experience, I added a regex match for urls following the pattern: https://tpc.googlesyndication.com/sodar/(.*).html to bypass leaving the application.
Please let me know if this works
Thanks
Ray
=> Adding Syndication Regex to Bypass openURL

Project/youtube-player-ios-example/Podfile, Project/youtube-player-ios-example/youtube-player-ios-example.xcodeproj/project.pbxproj, Project/youtube-player-ios-example/youtube-player-ios-example/PlaylistViewController.h, Project/youtube-player-ios-example/youtube-player-ios-example/SingleVideoViewController.h
Using Cocoapods 1.8.4 you couldn't build and run the sample app in the Project directory.
=> Fix Podfile of sample app

Classes/YTPlayerView.m
Follow-up to PR #362: Missing a `return` statement in several places, which resulted in the incorrect completionHandler being called. This could lead to crashes if the callback result is empty or represents an unexpected type.
=> Fix stopping callback when completionHandler has been called already.

Classes/YTPlayerView.m
Otherwise if an app contains any Uppercasing in its name, we were encountering an issue in which request.URL.host and originURL.host were using different casing even tho the strings were the same and that was making the isEqual comparison fail.
Didn't encounter this issue before because the sample app we test against does not contain Uppercase in its name.
This fixes issue #374.
=> Compare request.URL and originURL using lowercase Strings

Rakefile
The podspec has the fields s.version and s.source.tag that should use the same version given how  the repo is released right now. The Rakefile was only updating s.version but now s.source.tag is updated too.
=> Replace version number where needed in podspec

youtube-ios-player-helper/Assets.bundle/Assets/YTPlayerView-iframe-player.html
Reference screenshots:
[Before](https://ibb.co/hH9dmN8)
[After](https://ibb.co/hymvzhF)
If we define a viewport meta tag we can scale the player UI components to the desired size for the current device. In a webView if we don't specify it, the UI elements are very small.
=> Add viewport meta tag

Classes/YTPlayerView.m
The web iFrame embedded player may use Javascript to open the URL for some UI elements. WKWebView ignores this navigation by default, so this change adds the logic to link to the YT app. 
Tested on iPhone 12 Simulator, iOS 14.4. Verified that tapping on the video title links you to YT app site on Safari. Would redirect you to the YT main app if it was installed on the device.
=> Handle Javascript-based navigation for iFrame player in WKWebView
